# Generated by Django 4.2.2 on 2023-06-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=50),
        ),
    ]
